BEGIN;

INSERT INTO public.modules (name, display_name, description)
VALUES (
  'triagem_social',
  'Triagem Social',
  'Fila operacional do Servico Social para casos em fila de espera'
)
ON CONFLICT (name) DO UPDATE
SET display_name = EXCLUDED.display_name,
    description = EXCLUDED.description;

INSERT INTO public.permissions (name, display_name, description)
VALUES
  ('view', 'Visualizar', 'Permite visualizar registros do modulo'),
  ('create', 'Criar', 'Permite criar novos registros no modulo'),
  ('edit', 'Editar', 'Permite editar registros existentes no modulo')
ON CONFLICT (name) DO UPDATE
SET display_name = EXCLUDED.display_name,
    description = EXCLUDED.description;

DO $$
DECLARE
  patients_id_type text;
BEGIN
  SELECT format_type(a.atttypid, a.atttypmod)
    INTO patients_id_type
  FROM pg_attribute a
  JOIN pg_class c ON c.oid = a.attrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relname = 'patients'
    AND a.attname = 'id'
    AND a.attnum > 0
    AND NOT a.attisdropped
  LIMIT 1;

  IF patients_id_type IS NULL THEN
    RAISE EXCEPTION 'Nao foi possivel inferir o tipo de public.patients.id';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'social_triage_cases'
  ) THEN
    EXECUTE format(
      '
        CREATE TABLE public.social_triage_cases (
          id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
          patient_id %s NOT NULL UNIQUE,
          triagem_status text NOT NULL DEFAULT ''novo'',
          triagem_prioridade text NOT NULL DEFAULT ''normal'',
          triagem_responsavel_id text,
          triagem_responsavel_nome text,
          triagem_last_contact_at timestamptz,
          triagem_next_action_at timestamptz,
          triagem_notes_summary text,
          entrevista_agendada_flag boolean NOT NULL DEFAULT false,
          linked_appointment_id text,
          linked_appointment_at timestamptz,
          created_by text,
          updated_by text,
          created_at timestamptz NOT NULL DEFAULT NOW(),
          updated_at timestamptz NOT NULL DEFAULT NOW(),
          CONSTRAINT social_triage_cases_patient_fkey
            FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE,
          CONSTRAINT social_triage_cases_status_check
            CHECK (
              triagem_status IN (
                ''novo'',
                ''sem_contato'',
                ''tentativa_contato'',
                ''aguardando_retorno'',
                ''em_atendimento_social'',
                ''pre_cadastro_em_andamento'',
                ''aguardando_documentos'',
                ''apto_para_agendamento'',
                ''entrevista_agendada'',
                ''pausa_operacional''
              )
            ),
          CONSTRAINT social_triage_cases_prioridade_check
            CHECK (triagem_prioridade IN (''normal'', ''prioritario'', ''urgente''))
        )
      ',
      patients_id_type
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'social_triage_history'
  ) THEN
    EXECUTE format(
      '
        CREATE TABLE public.social_triage_history (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          triage_case_id uuid,
          patient_id %s NOT NULL,
          action_type text NOT NULL,
          field_name text,
          old_value text,
          new_value text,
          note text,
          metadata jsonb NOT NULL DEFAULT ''{}''::jsonb,
          acted_by text,
          acted_at timestamptz NOT NULL DEFAULT NOW(),
          CONSTRAINT social_triage_history_case_fkey
            FOREIGN KEY (triage_case_id) REFERENCES public.social_triage_cases(id) ON DELETE SET NULL,
          CONSTRAINT social_triage_history_patient_fkey
            FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE
        )
      ',
      patients_id_type
    );
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_social_triage_cases_patient
  ON public.social_triage_cases (patient_id);

CREATE INDEX IF NOT EXISTS idx_social_triage_cases_status_prioridade
  ON public.social_triage_cases (triagem_status, triagem_prioridade);

CREATE INDEX IF NOT EXISTS idx_social_triage_cases_responsavel
  ON public.social_triage_cases (triagem_responsavel_id);

CREATE INDEX IF NOT EXISTS idx_social_triage_cases_last_contact
  ON public.social_triage_cases (triagem_last_contact_at DESC);

CREATE INDEX IF NOT EXISTS idx_social_triage_cases_next_action
  ON public.social_triage_cases (triagem_next_action_at ASC NULLS LAST);

CREATE INDEX IF NOT EXISTS idx_social_triage_history_patient
  ON public.social_triage_history (patient_id, acted_at DESC);

CREATE INDEX IF NOT EXISTS idx_social_triage_history_case
  ON public.social_triage_history (triage_case_id, acted_at DESC);

CREATE INDEX IF NOT EXISTS idx_social_triage_history_action_type
  ON public.social_triage_history (action_type);

INSERT INTO public.social_triage_cases (
  patient_id,
  triagem_status,
  triagem_prioridade,
  created_at,
  updated_at
)
SELECT
  p.id,
  CASE
    WHEN LOWER(COALESCE(p.status, '')) = 'pre_cadastro' THEN 'pre_cadastro_em_andamento'
    ELSE 'novo'
  END AS triagem_status,
  'normal' AS triagem_prioridade,
  NOW(),
  NOW()
FROM public.patients p
WHERE LOWER(COALESCE(p.status_jornada, '')) = 'em_fila_espera'
  AND NOT EXISTS (
    SELECT 1
    FROM public.social_triage_cases st
    WHERE st.patient_id::text = p.id::text
  );

INSERT INTO public.social_triage_history (
  triage_case_id,
  patient_id,
  action_type,
  field_name,
  old_value,
  new_value,
  note,
  metadata,
  acted_by,
  acted_at
)
SELECT
  st.id,
  st.patient_id,
  'backfill_inicial',
  'triagem_status',
  NULL,
  st.triagem_status,
  'Backfill inicial da fila operacional de triagem social',
  jsonb_build_object('source', 'migration_202603221030'),
  NULL,
  NOW()
FROM public.social_triage_cases st
WHERE NOT EXISTS (
  SELECT 1
  FROM public.social_triage_history h
  WHERE h.triage_case_id = st.id
    AND h.action_type = 'backfill_inicial'
);

COMMIT;
