-- Up migration: normaliza funcoes de profissionais e adiciona role_id em professionals
-- Idempotente para execucao segura em ambientes que ja tenham parte da estrutura.

BEGIN;

CREATE TABLE IF NOT EXISTS public.professional_roles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS professional_roles_nome_unique_idx
  ON public.professional_roles (LOWER(nome));

ALTER TABLE public.professionals
  ADD COLUMN IF NOT EXISTS role_id integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'professionals_role_id_fkey'
      AND conrelid = 'public.professionals'::regclass
  ) THEN
    ALTER TABLE public.professionals
      ADD CONSTRAINT professionals_role_id_fkey
      FOREIGN KEY (role_id)
      REFERENCES public.professional_roles(id)
      ON UPDATE CASCADE
      ON DELETE SET NULL;
  END IF;
END $$;

INSERT INTO public.professional_roles (nome, ativo)
VALUES
  ('Psicologo', true),
  ('Fonoaudiologo', true),
  ('Assistente Social', true),
  ('Terapeuta Ocupacional', true),
  ('Fisioterapeuta', true),
  ('Psicopedagogo', true),
  ('Pedagogo', true),
  ('Nutricionista', true),
  ('Enfermeiro', true)
ON CONFLICT DO NOTHING;

-- Compatibilidade: tenta vincular role_id para registros antigos com funcao textual.
UPDATE public.professionals p
SET role_id = pr.id
FROM public.professional_roles pr
WHERE p.role_id IS NULL
  AND p.funcao IS NOT NULL
  AND LOWER(TRIM(p.funcao)) = LOWER(TRIM(pr.nome));

COMMIT;
