BEGIN;

ALTER TABLE public.patients
  ADD COLUMN IF NOT EXISTS status_jornada text;

UPDATE public.patients
SET status_jornada = 'em_fila_espera'
WHERE status_jornada IS NULL
   OR BTRIM(status_jornada) = '';

ALTER TABLE public.patients
  ALTER COLUMN status_jornada SET DEFAULT 'em_fila_espera',
  ALTER COLUMN status_jornada SET NOT NULL;

DO $$
DECLARE
  users_id_type text;
  patients_id_type text;
  changed_by_column_type text;
BEGIN
  SELECT format_type(a.atttypid, a.atttypmod)
    INTO users_id_type
  FROM pg_attribute a
  JOIN pg_class c ON c.oid = a.attrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relname = 'users'
    AND a.attname = 'id'
    AND a.attnum > 0
    AND NOT a.attisdropped
  LIMIT 1;

  SELECT format_type(a.atttypid, a.atttypmod)
    INTO patients_id_type
  FROM pg_attribute a
  JOIN pg_class c ON c.oid = a.attrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relname = 'patients'
    AND a.attname = 'id'
    AND a.attnum > 0
    AND NOT a.attisdropped
  LIMIT 1;

  IF users_id_type IS NULL OR patients_id_type IS NULL THEN
    RAISE EXCEPTION 'Nao foi possivel inferir os tipos de public.users.id/public.patients.id';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'assistido_status_history'
  ) THEN
    EXECUTE format(
      '
        CREATE TABLE public.assistido_status_history (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          assistido_id %s NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
          status_anterior text NULL,
          status_novo text NOT NULL,
          changed_by %s NULL REFERENCES public.users(id) ON DELETE SET NULL,
          motivo text NULL,
          changed_at timestamptz NOT NULL DEFAULT NOW()
        )
      ',
      patients_id_type,
      users_id_type
    );
  ELSE
    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'assistido_status_history'
        AND column_name = 'assistido_id'
    ) THEN
      EXECUTE format(
        'ALTER TABLE public.assistido_status_history ADD COLUMN assistido_id %s',
        patients_id_type
      );
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'assistido_status_history'
        AND column_name = 'status_anterior'
    ) THEN
      ALTER TABLE public.assistido_status_history
        ADD COLUMN status_anterior text;
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'assistido_status_history'
        AND column_name = 'status_novo'
    ) THEN
      ALTER TABLE public.assistido_status_history
        ADD COLUMN status_novo text;
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'assistido_status_history'
        AND column_name = 'changed_by'
    ) THEN
      EXECUTE format(
        'ALTER TABLE public.assistido_status_history ADD COLUMN changed_by %s',
        users_id_type
      );
    ELSE
      SELECT format_type(a.atttypid, a.atttypmod)
        INTO changed_by_column_type
      FROM pg_attribute a
      JOIN pg_class c ON c.oid = a.attrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = 'public'
        AND c.relname = 'assistido_status_history'
        AND a.attname = 'changed_by'
        AND a.attnum > 0
        AND NOT a.attisdropped
      LIMIT 1;

      IF changed_by_column_type IS DISTINCT FROM users_id_type THEN
        IF users_id_type = 'uuid' THEN
          UPDATE public.assistido_status_history
          SET changed_by = NULL
          WHERE changed_by IS NOT NULL
            AND changed_by::text !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$';
        ELSIF users_id_type IN ('smallint', 'integer', 'bigint') THEN
          UPDATE public.assistido_status_history
          SET changed_by = NULL
          WHERE changed_by IS NOT NULL
            AND changed_by::text !~ '^[0-9]+$';
        END IF;

        EXECUTE format(
          'ALTER TABLE public.assistido_status_history
             ALTER COLUMN changed_by TYPE %s
             USING NULLIF(BTRIM(changed_by::text), '''')::%s',
          users_id_type,
          users_id_type
        );
      END IF;
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'assistido_status_history'
        AND column_name = 'motivo'
    ) THEN
      ALTER TABLE public.assistido_status_history
        ADD COLUMN motivo text;
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'assistido_status_history'
        AND column_name = 'changed_at'
    ) THEN
      ALTER TABLE public.assistido_status_history
        ADD COLUMN changed_at timestamptz;
    END IF;
  END IF;
END $$;

UPDATE public.assistido_status_history
SET status_anterior = NULL
WHERE status_anterior IS NOT NULL
  AND BTRIM(status_anterior) = '';

UPDATE public.assistido_status_history
SET status_novo = 'em_fila_espera'
WHERE status_novo IS NULL
   OR BTRIM(status_novo) = '';

UPDATE public.assistido_status_history
SET changed_at = NOW()
WHERE changed_at IS NULL;

DELETE FROM public.assistido_status_history
WHERE assistido_id IS NULL;

ALTER TABLE public.assistido_status_history
  ALTER COLUMN status_novo SET NOT NULL,
  ALTER COLUMN changed_by DROP NOT NULL,
  ALTER COLUMN changed_at SET DEFAULT NOW(),
  ALTER COLUMN changed_at SET NOT NULL,
  ALTER COLUMN assistido_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'assistido_status_history_assistido_id_fkey'
      AND conrelid = 'public.assistido_status_history'::regclass
  ) THEN
    ALTER TABLE public.assistido_status_history
      ADD CONSTRAINT assistido_status_history_assistido_id_fkey
      FOREIGN KEY (assistido_id) REFERENCES public.patients(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'assistido_status_history_changed_by_fkey'
      AND conrelid = 'public.assistido_status_history'::regclass
  ) THEN
    ALTER TABLE public.assistido_status_history
      ADD CONSTRAINT assistido_status_history_changed_by_fkey
      FOREIGN KEY (changed_by) REFERENCES public.users(id) ON DELETE SET NULL;
  END IF;
END $$;

INSERT INTO public.assistido_status_history (
  assistido_id,
  status_anterior,
  status_novo,
  changed_by,
  motivo,
  changed_at
)
SELECT
  p.id,
  NULL,
  p.status_jornada,
  p.created_by,
  'Backfill inicial de jornada',
  COALESCE(p.updated_at, p.created_at, NOW())
FROM public.patients p
WHERE NOT EXISTS (
  SELECT 1
  FROM public.assistido_status_history h
  WHERE h.assistido_id::text = p.id::text
    AND h.status_anterior IS NULL
);

WITH ranked_initial AS (
  SELECT
    id,
    ROW_NUMBER() OVER (
      PARTITION BY assistido_id
      ORDER BY changed_at ASC, id ASC
    ) AS rn
  FROM public.assistido_status_history
  WHERE status_anterior IS NULL
)
DELETE FROM public.assistido_status_history h
USING ranked_initial r
WHERE h.id = r.id
  AND r.rn > 1;

CREATE INDEX IF NOT EXISTS idx_patients_status_jornada
  ON public.patients (status_jornada);

CREATE INDEX IF NOT EXISTS idx_assistido_status_history_assistido
  ON public.assistido_status_history (assistido_id, changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_assistido_status_history_changed_by
  ON public.assistido_status_history (changed_by);

CREATE UNIQUE INDEX IF NOT EXISTS idx_assistido_status_history_initial_status_unique
  ON public.assistido_status_history (assistido_id)
  WHERE status_anterior IS NULL;

COMMIT;
