BEGIN;

DO $$
DECLARE
  users_id_type text;
  patients_id_type text;
  decided_by_column_type text;
BEGIN
  SELECT format_type(a.atttypid, a.atttypmod)
    INTO users_id_type
  FROM pg_attribute a
  JOIN pg_class c ON c.oid = a.attrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relname = 'users'
    AND a.attname = 'id'
    AND a.attnum > 0
    AND NOT a.attisdropped
  LIMIT 1;

  SELECT format_type(a.atttypid, a.atttypmod)
    INTO patients_id_type
  FROM pg_attribute a
  JOIN pg_class c ON c.oid = a.attrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relname = 'patients'
    AND a.attname = 'id'
    AND a.attnum > 0
    AND NOT a.attisdropped
  LIMIT 1;

  IF users_id_type IS NULL OR patients_id_type IS NULL THEN
    RAISE EXCEPTION 'Nao foi possivel inferir os tipos de public.users.id/public.patients.id';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'assistido_vaga_decisions'
  ) THEN
    EXECUTE format(
      '
        CREATE TABLE public.assistido_vaga_decisions (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          assistido_id %s NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
          decisao text NOT NULL,
          justificativa text NOT NULL,
          decided_by %s NULL REFERENCES public.users(id) ON DELETE SET NULL,
          decided_at timestamptz NOT NULL DEFAULT NOW(),
          created_at timestamptz NOT NULL DEFAULT NOW()
        )
      ',
      patients_id_type,
      users_id_type
    );
  ELSE
    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'assistido_vaga_decisions'
        AND column_name = 'assistido_id'
    ) THEN
      EXECUTE format(
        'ALTER TABLE public.assistido_vaga_decisions ADD COLUMN assistido_id %s',
        patients_id_type
      );
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'assistido_vaga_decisions'
        AND column_name = 'decisao'
    ) THEN
      ALTER TABLE public.assistido_vaga_decisions
        ADD COLUMN decisao text;
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'assistido_vaga_decisions'
        AND column_name = 'justificativa'
    ) THEN
      ALTER TABLE public.assistido_vaga_decisions
        ADD COLUMN justificativa text;
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'assistido_vaga_decisions'
        AND column_name = 'decided_by'
    ) THEN
      EXECUTE format(
        'ALTER TABLE public.assistido_vaga_decisions ADD COLUMN decided_by %s',
        users_id_type
      );
    ELSE
      SELECT format_type(a.atttypid, a.atttypmod)
        INTO decided_by_column_type
      FROM pg_attribute a
      JOIN pg_class c ON c.oid = a.attrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = 'public'
        AND c.relname = 'assistido_vaga_decisions'
        AND a.attname = 'decided_by'
        AND a.attnum > 0
        AND NOT a.attisdropped
      LIMIT 1;

      IF decided_by_column_type IS DISTINCT FROM users_id_type THEN
        IF users_id_type = 'uuid' THEN
          UPDATE public.assistido_vaga_decisions
          SET decided_by = NULL
          WHERE decided_by IS NOT NULL
            AND decided_by::text !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$';
        ELSIF users_id_type IN ('smallint', 'integer', 'bigint') THEN
          UPDATE public.assistido_vaga_decisions
          SET decided_by = NULL
          WHERE decided_by IS NOT NULL
            AND decided_by::text !~ '^[0-9]+$';
        END IF;

        EXECUTE format(
          'ALTER TABLE public.assistido_vaga_decisions
             ALTER COLUMN decided_by TYPE %s
             USING NULLIF(BTRIM(decided_by::text), '''')::%s',
          users_id_type,
          users_id_type
        );
      END IF;
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'assistido_vaga_decisions'
        AND column_name = 'decided_at'
    ) THEN
      ALTER TABLE public.assistido_vaga_decisions
        ADD COLUMN decided_at timestamptz;
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'assistido_vaga_decisions'
        AND column_name = 'created_at'
    ) THEN
      ALTER TABLE public.assistido_vaga_decisions
        ADD COLUMN created_at timestamptz;
    END IF;
  END IF;
END $$;

UPDATE public.assistido_vaga_decisions
SET decisao = LOWER(BTRIM(decisao))
WHERE decisao IS NOT NULL
  AND decisao <> LOWER(BTRIM(decisao));

UPDATE public.assistido_vaga_decisions
SET decisao = 'encaminhado'
WHERE decisao IS NULL
   OR BTRIM(decisao) = ''
   OR LOWER(BTRIM(decisao)) NOT IN ('aprovado', 'encaminhado');

UPDATE public.assistido_vaga_decisions
SET justificativa = 'Sem justificativa informada'
WHERE justificativa IS NULL
   OR BTRIM(justificativa) = '';

UPDATE public.assistido_vaga_decisions
SET decided_at = NOW()
WHERE decided_at IS NULL;

UPDATE public.assistido_vaga_decisions
SET created_at = COALESCE(created_at, decided_at, NOW())
WHERE created_at IS NULL;

DELETE FROM public.assistido_vaga_decisions
WHERE assistido_id IS NULL;

ALTER TABLE public.assistido_vaga_decisions
  ALTER COLUMN assistido_id SET NOT NULL,
  ALTER COLUMN decisao SET NOT NULL,
  ALTER COLUMN justificativa SET NOT NULL,
  ALTER COLUMN decided_by DROP NOT NULL,
  ALTER COLUMN decided_at SET DEFAULT NOW(),
  ALTER COLUMN decided_at SET NOT NULL,
  ALTER COLUMN created_at SET DEFAULT NOW(),
  ALTER COLUMN created_at SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'assistido_vaga_decisions_assistido_id_fkey'
      AND conrelid = 'public.assistido_vaga_decisions'::regclass
  ) THEN
    ALTER TABLE public.assistido_vaga_decisions
      ADD CONSTRAINT assistido_vaga_decisions_assistido_id_fkey
      FOREIGN KEY (assistido_id) REFERENCES public.patients(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'assistido_vaga_decisions_decided_by_fkey'
      AND conrelid = 'public.assistido_vaga_decisions'::regclass
  ) THEN
    ALTER TABLE public.assistido_vaga_decisions
      ADD CONSTRAINT assistido_vaga_decisions_decided_by_fkey
      FOREIGN KEY (decided_by) REFERENCES public.users(id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'assistido_vaga_decisions_decisao_check'
      AND conrelid = 'public.assistido_vaga_decisions'::regclass
  ) THEN
    ALTER TABLE public.assistido_vaga_decisions
      ADD CONSTRAINT assistido_vaga_decisions_decisao_check
      CHECK (decisao IN ('aprovado', 'encaminhado'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_assistido_vaga_decisions_assistido_decided_at
  ON public.assistido_vaga_decisions (assistido_id, decided_at DESC);

CREATE INDEX IF NOT EXISTS idx_assistido_vaga_decisions_decisao
  ON public.assistido_vaga_decisions (decisao);

COMMIT;
