// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkxbtszvrqgaovxgojrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhreGJ0c3p2cnFnYW92eGdvanJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjM1NzcsImV4cCI6MjA2OTYzOTU3N30.b_oEIXWVqpyV4wiq_47CTsA9gYQLqV7PkFVa1rh5tVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});